title: みずたまり
email: github@c-uo.dev
description: >- # this means to ignore newlines until "baseurl:"
  まだ何も書いていない
# baseurl: "/docs" # the subpath of your site, e.g. /blog
domain: c-uo.dev
url: "https://blog.c-uo.dev" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: 
github_username:  C-uo

# Build settings
markdown: GFM
theme: minima
plugins:
  - jekyll-feed

